// demos/react/App.tsx
import { useEffect, useRef } from 'react';
import UniversalScrollbar from 'universal-scrollbar';

function App() {
  const containerRef = useRef<HTMLDivElement>(null);
  const scrollbarRef = useRef<UniversalScrollbar | null>(null);

  useEffect(() => {
    if (containerRef.current) {
      scrollbarRef.current = new UniversalScrollbar({
        target: containerRef.current,
        thumbColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        autoHide: true,
      });
    }
    return () => {
      scrollbarRef.current?.destroy();
    };
  }, []);

  const lines = Array.from({ length: 25 }, (_, i) => `Line ${i + 1}`);

  return (
    <div>
      <h1>React demo</h1>
      <p>Custom scrollbar on a scrollable container via ref.</p>
      <div
        ref={containerRef}
        className="scroll-container"
        style={{ maxHeight: '300px', overflow: 'auto' }}
      >
        {lines.map((line) => (
          <p key={line}>{line}</p>
        ))}
      </div>
    </div>
  );
}

export default App;

// demos/vue/App.vue
<template>
  <div>
    <h1>Vue demo</h1>
    <p>Custom scrollbar via composable and ref.</p>
    <div
      ref="containerRef"
      class="scroll-container"
      style="max-height: 300px; overflow: auto"
    >
      <p v-for="i in 25" :key="i">Line {{ i }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import UniversalScrollbar from 'universal-scrollbar';

const containerRef = ref<HTMLElement | null>(null);
let scrollbar: UniversalScrollbar | null = null;

onMounted(() => {
  if (containerRef.value) {
    scrollbar = new UniversalScrollbar({
      target: containerRef.value,
      thumbColor: '#667eea',
      autoHide: true,
    });
  }
});

onUnmounted(() => {
  scrollbar?.destroy();
});
</script>
