// demos/angular/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import UniversalScrollbar from 'universal-scrollbar';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements AfterViewInit, OnDestroy {
  @ViewChild('scrollRef') scrollRef!: ElementRef<HTMLDivElement>;
  private scrollbar: UniversalScrollbar | null = null;
  lines = Array.from({ length: 25 }, (_, i) => i + 1);

  ngAfterViewInit(): void {
    const el = this.scrollRef?.nativeElement;
    if (el) {
      setTimeout(() => {
        this.scrollbar = new UniversalScrollbar({
          target: el,
          autoHide: false,
          thumbColor: '#667eea',
        });
      }, 0);
    }
  }

  ngOnDestroy(): void {
    this.scrollbar?.destroy();
  }
}

<h1>Angular demo</h1>
<p>Custom scrollbar via ViewChild and AfterViewInit.</p>
<div
  #scrollRef
  class="scroll-area"
  style="max-height: 300px; overflow: auto; padding: 12px; border: 1px solid #eee; border-radius: 8px;"
>
  @for (i of lines; track i) {
    <p>Line {{ i }}</p>
  }
</div>

// demos/svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import UniversalScrollbar from 'universal-scrollbar';

  let scrollContainer: HTMLDivElement;
  let scrollbar: UniversalScrollbar | null = null;

  onMount(() => {
    if (scrollContainer) {
      requestAnimationFrame(() => {
        scrollbar = new UniversalScrollbar({
          target: scrollContainer,
          autoHide: false,
          thumbColor: '#667eea',
        });
      });
    }
  });

  onDestroy(() => {
    scrollbar?.destroy();
  });
</script>

<main>
  <h1>Svelte demo</h1>
  <p>Custom scrollbar on a scrollable container via bind:this.</p>
  <div
    bind:this={scrollContainer}
    class="scroll-area"
    style="max-height: 300px; overflow: auto; padding: 12px; border: 1px solid #eee; border-radius: 8px;"
  >
    {#each Array(25) as _, i}
      <p style="margin: 0 0 8px;">Line {i + 1}</p>
    {/each}
  </div>
</main>

<style>
  main {
    font-family: system-ui, sans-serif;
    padding: 20px;
  }
</style>
